/**
 * Compiles the curated Material Symbols Rounded icons into a typed path map, so the 5 MB icon font is never shipped.
 * Usage: pnpm icons   (reads components/icons/icon-names.ts, writes components/icons/registry.ts)
 *
 * Source: node_modules/@material-symbols/svg-400/rounded/<name>.svg (wght 400, FILL 0, GRAD 0; the package only
 * ships the opsz 48 master, drawn on the same 960-unit grid as opsz 24).
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ICON_ALIASES, ICON_NAMES, type IconSourceName } from "../components/icons/icon-names";

const root = process.cwd();
const sourceDir = join(root, "node_modules", "@material-symbols", "svg-400", "rounded");
const target = join(root, "components", "icons", "registry.ts");

const PATH_D = /<path\b[^>]*?\sd="([^"]+)"/g;
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Every icon in the package is a single <path>. Anything else (several paths, circles, groups) is reported as missing
 * rather than guessed at: joining paths would change the meaning of a leading relative "m".
 */
function extractPathData(svg: string): string | null {
  if (/<(circle|ellipse|rect|polygon|polyline|line|g)\b/.test(svg)) return null;
  const matches = [...svg.matchAll(PATH_D)];
  if (matches.length !== 1) return null;
  return matches[0]?.[1]?.trim() || null;
}

function readIcon(name: IconSourceName): { d: string; file: string } | null {
  const file = ICON_ALIASES[name] ?? name;
  const path = join(sourceDir, `${file}.svg`);
  if (!existsSync(path)) return null;
  const d = extractPathData(readFileSync(path, "utf8"));
  return d ? { d, file } : null;
}

function main(): void {
  if (!existsSync(sourceDir)) {
    console.error(`Missing ${sourceDir}. Run pnpm install first.`);
    process.exit(1);
  }

  const names = [...new Set(ICON_NAMES)].sort();
  const entries: string[] = [];
  const missing: string[] = [];

  for (const name of names) {
    const icon = readIcon(name);
    if (!icon) {
      missing.push(name);
      continue;
    }
    const key = IDENTIFIER.test(name) ? name : JSON.stringify(name);
    const note = icon.file === name ? "" : ` // svg: ${icon.file}`;
    entries.push(`  ${key}: ${JSON.stringify(icon.d)},${note}`);
  }

  const source = [
    "// Generated by scripts/gen-icons.ts from @material-symbols/svg-400 (rounded). Do not edit; run `pnpm icons`.",
    "",
    "/** SVG path data (viewBox \"0 -960 960 960\") for each curated Material Symbols Rounded icon. */",
    "export const ICON_PATHS = {",
    ...entries,
    "} as const;",
    "",
    "export type IconName = keyof typeof ICON_PATHS;",
    "",
  ].join("\n");

  writeFileSync(target, source, "utf8");
  console.info(`Wrote ${entries.length} icons to components/icons/registry.ts`);
  for (const name of missing) {
    console.warn(`warning: icon "${name}" not found in @material-symbols/svg-400/rounded; skipped`);
  }
}

main();
